#!/bin/sh
CURRENT=`cat ~/.rakudobrew/CURRENT`
TYPE=`echo $CURRENT | sed -e 's/\-.*$//'`

if [ $TYPE = 'jvm' ]; then
    ~/.rakudobrew/$CURRENT/nqp/install/nqp "$@"
elif [ $TYPE = 'parrot' ]; then
    ~/.rakudobrew/$CURRENT/nqp/nqp "$@"
else
    echo "I don't know how to run nqp on $CURRENT :("
fi
