#!/bin/sh

CURRENT=`cat ~/.rakudobrew/CURRENT`
TYPE=`echo $CURRENT | sed -e 's/\-.*$//'`

if [ $TYPE = 'jvm' ]; then
    ~/.rakudobrew/run-jvm "$@"
elif [ $TYPE = 'parrot' ]; then
    ~/.rakudobrew/$CURRENT/install/bin/perl6 "$@"
else
    echo "I don't know how to run $CURRENT :("
fi
